name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4 15 * *'
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0    
      
    - name: Login to Github Package Repo
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    -  name: Build and Push to Docker Package Repo
       id: docker_build
       uses: mr-smithers-excellent/docker-build-push@v5.6
       with:
         image: awx-cloud-ee
         registry: ghcr.io
         githubOrg: epod
         dockerfile: Containerfile
         tags: latest  
